command /duelsands [<player>] [<text>]:
    trigger:
        if arg-1 is offline player:
            if arg-2 is not set:
                if arg-1 is player:
                    send "You have to challange other players"
                    stop
                send component mini message from "<green>-----------------------------------------------</green>%newline%<aqua>%player%</aqua> <gray>is challanging you to duel in sands</gray><click:run_command:/duelsands %player% accept>%newline%<hover:show_text:Click to accept %player%'s challange><aqua>[Click to accept]</aqua></hover></click>%newline%<green>-----------------------------------------------</green>" to arg-1
                set {duelSands:%player%.%arg-1%} to 1
            else if arg-2 is "accept":
                set {duelSands:%arg-1%.%player%} to 2

every tick:
    loop {duelSands:*}:
        if loop-value is 2:
            


function duelSands(challanger: player, challanged: player):
    open chest inventory with 5 rows named "&6Sands" to challanger